# Generated by Django 2.2.5 on 2022-02-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlants',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=250)),
                ('net_generation', models.FloatField()),
            ],
        ),
    ]
